apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/phclark/kargo-demo
      writeBranch: main
      helm:
        images:
          - image: nginx
            key: onechart.image.tag
            value: Tag
            valuesFilePath: environments/dev/demo/values.yaml
        charts:
          - name: gimlet-io/onechart
            chartPath: environments/dev/demo/Chart.yaml
            registryURL: "oci://ghcr.io/"
            