apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/phclark/kargo-demo
      writeBranch: main
      helm:
        images:
          - image: nginx
            key: onechart.image.tag
            value: Tag
            valuesFilePath: environments/test/demo/values.yaml
        charts:
          - name: onechart
            chartPath: environments/test/demo/Chart.yaml
            registryURL: oci://ghcr.io/gimlet-io