apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/phclark/kargo-demo
      writeBranch: main
      helm:
        images:
          - image: nginx
            key: onechart.image.tag
            value: Tag
            valuesFilePath: environments/prod/demo/values.yaml
        charts:
          - name: onechart
            chartPath: environments/prod/demo/Chart.yaml
            registryURL: "oci://ghcr.io/gimlet-io/onechart"