apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: nginx
      semverConstraint: "~1.20.0"
  - chart:
      name: onechart
      registryURL: "oci://ghcr.io/gimlet-io/onechart"
      # semverConstraint: "~0.62.0"
