mariadb:
  enabled: false

wordpress:
  image:
    tag: 6.4.2-debian-11-r10
  wordpressBlogName: Dev Blog
  
  wordpressPassword: foo
  mariadb:
    enabled: false
  externalDatabase:
    host: localhost
    user: bn_wordpress
    password: ""
    database: bitnami_wordpress
    port: 3306